config/routes.rb
Brainreserve::Application.routes.draw do

  

  
  resources :invitations

  resources :articles do
      resources :comments
  end

  match '/comments/approve/:id' => 'comments#approve'
  match '/articles/toggledisplay/:id' => 'articles#toggledisplay'
  match '/thebrain' => 'articles#thebrain'
  match '/thebrain/straightfromfaith' => 'articles#straightfromfaith'
  match '/thebrain/fromthetrenddesk' => 'articles#fromthetrenddesk'
  match '/thebrain/predictions' => 'articles#predictions'
  match '/thebrain/thetalentnetwork' => 'articles#talentnetwork'
  
  
  resources :predictions
  resources :articles
  resources :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
   validates :email, :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i},
                    :presence => true,
                    :length => {:minimum => 3, :maximum => 254}
  validates :content, :presence => true
  validates :name, :presence => true
  belongs_to :article


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # GET /comments
  # GET /comments.xml
  def index
    @article = Article.find(params[:article_id])
    @comments = @article.comments.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])

    respond_to do |format|
      format.html # Commentshow.html.erb
      format.xml  { render :xml => @comment }
    end
  end


  def approve
    @article = Article.find(params[:article_id])
   @comment = Comment.find(params[:id])
    if (params[:direction] == 'approve')
      @comment.approved = true

    else
      @comment.approved = false
    end

    if @comment.update_attributes(:approved)
       redirect_to article_comment_path, :action => :index, :notice => 'Comment was approved'
    else
       redirect_to article_comment_path, :action => :index, :notice => 'Comment could not be approved!'
    end


  end

  # GET /comments/new
  # GET /comments/new.xmledit_topic_path(@topic)
  def new
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new

    respond_to do |format|
      format.html  # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @article = Article.find(params[:article_id])
   @comment = @article.comments.find(params[:id])
  end

  # POST /commentsrender :action => index"
  # POST /comments.xml
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(params[:comment])

    respond_to do |format|
      if @comment.save
        redirect_to article_comments_path(@article), :action => :index, :notice => 'Thank you for your comment'
      else
        redirect_to article_comments_path(@article), :action => :index, :notice => "Can't add comment"
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@comment, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @topic = Article.find(params[:article_id])
    @comment = @topic.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(comments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@article,@comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :approved %><br />
    <%= f.check_box :approved %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
     <%= f.hidden_field :article_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', article_comment_path %> |
<%= link_to 'Back', article_comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments for Article <%=  @article.id %></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Approved</th>
    <th>Content</th>
    <th>Email</th>
    <th>Article</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.approved %></td>
    <td><%= comment.content %></td>
    <td><%= comment.email %></td>
    <td><%= link_to 'Show', article_comment_path(@article, comment) %></td>
    <td><%= link_to 'Edit', edit_article_comment_path(@article, comment) %></td>
    <td><%= link_to 'Delete', article_comment_path(@article, comment), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_article_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', article_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Approved:</b>
  <%= @comment.approved %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>

<p>
  <b>Email:</b>
  <%= @comment.email %>
</p>

<p>
  <b>Article:</b>
  <%= @comment.article.title %>
</p>



<%= link_to 'Edit', edit_article_comment_path(@article) %> |
<%= link_to 'Back', article_comments_path(@article) %>