config/routes.rb
Brainreserve::Application.routes.draw do

  

  
  resources :invitations

  resources :articles do
      resources :comments
  end

  match '/comments/approve/:id' => 'comments#approve'
  match '/articles/toggledisplay/:id' => 'articles#toggledisplay'
  match '/thebrain' => 'articles#thebrain'
  match '/thebrain/straightfromfaith' => 'articles#straightfromfaith'
  match '/thebrain/fromthetrenddesk' => 'articles#fromthetrenddesk'
  match '/thebrain/predictions' => 'articles#predictions'
  match '/thebrain/thetalentnetwork' => 'articles#talentnetwork'
  
  
  resources :predictions
  resources :articles
  resources :comments

end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
  validates :email, :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i},
                    :presence => true,
                    :length => {:minimum => 3, :maximum => 254}
  validates :content, :presence => true
  validates :name, :presence => true
  belongs_to :topic
  
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  # GET /predictions
  # GET /predictions.xml
  def index
    @topic = Topic.find(params[:topic_id])
    @predictions = @topic.predictions.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @predictions }
    end
  end

  # GET /predictions/1
  # GET /predictions/1.xml
  def show
    @topic = Topic.find(params[:topic_id])
    @prediction = @topic.predictions.find(params[:id])

    respond_to do |format|
      format.html # Predictionshow.html.erb
      format.xml  { render :xml => @prediction }
    end
  end

  
  def approve
    @topic = Topic.find(params[:topic_id])
   @prediction = Prediction.find(params[:id])
    if (params[:direction] == 'approve')
      @prediction.approved = true
      
    else
      @prediction.approved = false
    end
    
    if @prediction.update_attributes(:approved)
       redirect_to :action => :index, :notice => 'Prediction was approved'
    else
       redirect_to :action => :index, :notice => 'Prediction could not be approved!'
    end
  end

  # GET /predictions/new
  # GET /predictions/new.xmledit_topic_path(@topic)
  def new
    @topic = Topic.find(params[:topic_id])
    @prediction = Prediction.new

    respond_to do |format|
      format.html  # new.html.erb
      format.xml  { render :xml => @prediction }
    end
  end

  # GET /predictions/1/edit
  def edit
    @topic = Topic.find(params[:topic_id])
   @prediction = @topic.predictions.find(params[:id])
  end

  # POST /predictionsrender :action => index"
  # POST /predictions.xml
  def create
    @topic = Topic.find(params[:topic_id])
    @prediction = @topic.predictions.new(params[:prediction])

    respond_to do |format|
      if @prediction.save
        format.html { redirect_to(@prediction, :notice => 'Prediction was successfully created.') }
        format.xml  { render :xml => @prediction, :status => :created, :location => @prediction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @prediction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /predictions/1
  # PUT /predictions/1.xml
  def update
    @topic = Topic.find(params[:topic_id])
    @prediction = @topic.predictions.find(params[:id])

    respond_to do |format|
      if @prediction.update_attributes(params[:prediction])
        format.html { redirect_to(@prediction, :notice => 'Prediction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @prediction.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /predictions/1
  # DELETE /predictions/1.xml
  def destroy
    @topic = Topic.find(params[:topic_id])
    @prediction = @topic.predictions.find(params[:id])
    @prediction.destroy

    respond_to do |format|
      format.html { redirect_to(predictions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/views/predictions/_form.html.erb
<%= form_for(@topic, @prediction) do |f| %>
  <% if @prediction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prediction.errors.count, "error") %> prohibited this prediction from being saved:</h2>

      <ul>
      <% @prediction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :approved %><br />
    <%= f.check_box :approved %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  
  </div>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/predictions/edit.html.erb
<h1>Editing prediction</h1>

<%= render 'form' %>

<%= link_to 'Show', @prediction %> |
<%= link_to 'Back', predictions_path %>

app/views/predictions/index.html.erb
<h1>Administration of Predictions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Approved</th>
    <th>Content</th>
    <th>Email</th>
    <th>Topic</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @predictions.each do |prediction| %>
  <tr>
    <td><%= prediction.name %></td>
    <td><%= if prediction.approved then 'Yes' else 'No' end %></td>
    <td><%= prediction.content %></td>
    <td><%= prediction.email %></td>
    <td><%= prediction.topic_id %></td>
    <td><%= link_to 'Show', prediction %></td>
    <td><%= link_to 'Edit', :method => :edit, :topic_id => @topic.id, :id => prediction.id %></td>
    <td><%= link_to 'Delete', prediction, :confirm => 'Are you Question	sure?', :method => :delete %></td>
    <td><%= if prediction.approved  then
                  link_to 'Disapprove For Display', :action => 'approve', :id => prediction.id, :direction => 'disapprove'
            else
                  link_to 'Approve For Display', :action => 'approve', :id => prediction.id, :direction => 'approve'
            end
         %></td>


  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prediction', new_topic_prediction_path(@topic, @prediction) %>

app/views/predictions/new.html.erb
<h1>New prediction</h1>

<%= render 'form' %>

<%= link_to 'Back', predictions_path %>

app/views/predictions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @prediction.name %>
</p>

<p>
  <b>Approved:</b>
  <%= @prediction.approved %>
</p>

<p>
  <b>Content:</b>
  <%= @prediction.content %>
</p>

<p>
  <b>Email:</b>
  <%= @prediction.email %>
</p>

<p>
  <b>Question:</b>
  <%= @prediction.question_id %>
</p>


<%= link_to 'Edit', edit_prediction_path(@prediction) %> |
<%= link_to 'Back', predictions_path %>