config/routes.rb
Brainreserve::Application.routes.draw do

  

  
  resources :invitations

  resources :articles do
      resources :comments
  end

  match '/comments/approve/:id' => 'comments#approve'
  match '/articles/toggledisplay/:id' => 'articles#toggledisplay'
  match '/thebrain' => 'articles#thebrain'
  match '/thebrain/straightfromfaith' => 'articles#straightfromfaith'
  match '/thebrain/fromthetrenddesk' => 'articles#fromthetrenddesk'
  match '/thebrain/predictions' => 'articles#predictions'
  match '/thebrain/thetalentnetwork' => 'articles#talentnetwork'
  
  
  resources :predictions
  resources :articles
  resources :comments

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  belongs_to :category
  
  validates :title, :presence => true, :uniqueness => true, :length => {:maximum => 60}
  validates :content, :presence => true
  validates :user, :presence => true
  validates :author, :presence => true
  validates :category_id, :presence => true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.xml

  before_filter :authenticate_user!, :except => [:straightfromfaith, :fromthetrenddesk, :talentbanknetwork, :predictions, :thebrain]
  def index
    # @articles = Article.find(:all, :order => :category_id)
    
    #show articles by category
    @articles_SFF = Article.where(:category_id => 1)
    @articles_FTD = Article.where(:category_id => 2)
    @articles_TBN = Article.where(:category_id => 3)
    @articles_P = Article.where(:category_id => 4)
    
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    
    end
  end



  def straightfromfaith
     @articles_SFF = Article.where(:category_id => 1, :isdisplayed => true)
     respond_to do |format|
      format.html # 
      format.xml  { render :xml => @article }
    end
  end

  def fromthetrenddesk
     @articles_FTD = Article.where(:category_id => 2, :isdisplayed => true)
     respond_to do |format|
      format.html # 
      format.xml  { render :xml => @article }
    end 
  end
 
  
  def talentbanknetwork
     @articles_TBN = Article.where(:category_id => 3, :isdisplayed => true)
     respond_to do |format|
      format.html # 
      format.xml  { render :xml => @article }
    end
  end
 
  
  def predictions
     @articles_P = Article.where(:category_id => 4, :isdisplayed => true)
      respond_to do |format|
      format.html # 
      format.xml  { render :xml => @article }
    end
  end

  def thebrain
    @articles_SFF = Article.where(:category_id => 1, :isdisplayed => true).limit(5)
    @articles_FTD = Article.where(:category_id => 2, :isdisplayed => true).limit(5)
    @articles_TBN = Article.where(:category_id => 3, :isdisplayed => true).limit(5)
    @articles_P = Article.where(:category_id => 4, :isdisplayed => true).limit(5)
    respond_to do |format|
      format.html # 
      format.xml  { render :xml => @article }
    end
  end

 

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  def toggledisplay
    @article = Article.find(params[:id])
    if (params[:direction] == 'display')
      @article.isdisplayed = true
    else
      @article.isdisplayed = false
    end

    if @article.update_attributes(:isdisplayed)
       redirect_to :action => :index
    else
       redirect_to :action => :index, :notice => 'Display could not be changed!'
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new
    @categories = Category.all
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
    @categories = Category.all
    
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<!-- Load jQuery -->
<script type="text/javascript" src="http://www.google.com/jsapi"></script>
<script type="text/javascript">
        google.load("jquery", "1.3");
</script>

<!-- Load jQuery build -->
<script type="text/javascript" src="/javascripts/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript">
tinyMCE.init({
        // General options
        mode : "textareas",
        theme : "advanced",
        plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",

        // Theme options
        theme_advanced_buttons1 : "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen",
        theme_advanced_buttons4 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true,

        // Example content CSS (should be your site CSS)
        content_css : "css/example.css",

        // Drop lists for link/image/media/template dialogs
        // template_external_list_url : "js/template_list.js",
        // external_link_list_url : "js/link_list.js",
        // external_image_list_url : "js/image_list.js",
        // media_external_list_url : "js/media_list.js",

        // Replace values for the template plugin
        template_replace_values : {
                username : "Some User",
                staffid : "991234"
        }
});
</script>


<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="tinymce">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>


  <div class="field">
    <%= f.hidden_field :user, :value => current_user.username %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.collection_select :category_id, @categories, :id, :name, :include_blank => 'Select a Category'  %>
  </div>
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/fromthetrenddesk.html.erb
<h1>From the Trend Desk</h1>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Author</th>
    <th></th>
  </tr>

<% @articles_FTD.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.user %></td>
    <td><%= article.author %></td>
    <td><%= link_to 'Show', article %></td>
  </tr>
<% end %>
  
</table>

<br />

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Author</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
    <th>Display Status</th>
    <th></th>
  </tr>

<% @articles_SFF.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.user %></td>
    <td><%= article.author %></td>
    <td><%= article.category.name %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Delete', article, :method => 'delete', :confirm => 'Are you sure you want to delete?' %></td>
    <td><b><%= if article.isdisplayed then
                  "*DISPLAYED*      " 
	    else
                  "*NOT DISPLAYED*  "
	    end
       %></b></td>
    <td><%= if article.isdisplayed then
           	  link_to 'Don\'t Display', :action => 'toggledisplay', :id => article.id, :direction => 'dontdisplay'
            else
           	  link_to 'Display', :action => 'toggledisplay', :id => article.id, :direction => 'display'
            end
       %></td>
  </tr>
<% end %>
  <tr>
    <td colspan="10"> &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
  </tr>
 <tr>
    <th>Title</th>
    <th>User</th>
    <th>Author</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
    <th>Display Status</th>
    <th></th>
  </tr>
  

<% @articles_FTD.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.user %></td>
    <td><%= article.author %></td>
    <td><%= article.category.name %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Delete', article, :method => 'delete', :confirm => 'Are you sure you want to delete?' %></td>
    <td><b><%= if article.isdisplayed then
                  "*DISPLAYED*      " 
	    else
                  "*NOT DISPLAYED*  "
	    end
       %></b></td>
    <td><%= if article.isdisplayed then
           	  link_to 'Don\'t Display', :action => 'toggledisplay', :id => article.id, :direction => 'dontdisplay'
            else
           	  link_to 'Display', :action => 'toggledisplay', :id => article.id, :direction => 'display'
            end
       %></td>
  </tr>
<% end %>
<tr>
    <td colspan="10"> &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
  </tr>
<tr>
    <th>Title</th>
    <th>User</th>
    <th>Author</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
    <th>Display Status</th>
    <th></th>
  </tr>


<% @articles_TBN.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.user %></td>
    <td><%= article.author %></td>
    <td><%= article.category.name %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Delete', article, :method => 'delete', :confirm => 'Are you sure you want to delete?' %></td>
    <td><b><%= if article.isdisplayed then
                  "*DISPLAYED*      " 
	    else
                  "*NOT DISPLAYED*  "
	    end
       %></b></td>
    <td><%= if article.isdisplayed then
           	  link_to 'Don\'t Display', :action => 'toggledisplay', :id => article.id, :direction => 'dontdisplay'
            else
           	  link_to 'Display', :action => 'toggledisplay', :id => article.id, :direction => 'display'
            end
       %></td>
  </tr>
<% end %>




<tr>
    <td colspan="10"> &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
  </tr>
<tr>
    <th>Title</th>
    <th>User</th>
    <th>Author</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
    <th>Display Status</th>
    <th></th>
  </tr>

<% @articles_P.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.user %></td>
    <td><%= article.author %></td>
    <td><%= article.category.name %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Delete', article, :method => 'delete', :confirm => 'Are you sure you want to delete?' %></td>
    <td><b><%= if article.isdisplayed then
                  "*DISPLAYED*      " 
	    else
                  "*NOT DISPLAYED*  "
	    end
       %></b></td>
    <td><%= if article.isdisplayed then
           	  link_to 'Don\'t Display', :action => 'toggledisplay', :id => article.id, :direction => 'dontdisplay'
            else
           	  link_to 'Display', :action => 'toggledisplay', :id => article.id, :direction => 'display'
            end
       %></td>
  </tr>
<% end %>




</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/predictions.html.erb
<h1>Predictions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Author</th>
    <th></th>
  </tr>

<% @articles_P.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.user %></td>
    <td><%= article.author %></td>
    <td><%= link_to 'Show', article %></td>
  </tr>
<% end %>
</table>

<br />

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Content:</b>
  <%= @article.content.html_safe %>
</p>

<p>
  <b>User:</b>
  <%= @article.user %>
</p>

<p>
  <b>Author:</b>
  <%= @article.author %>
</p>

<p>
  <b>Category:</b>
  <%= @article.category.name %>
</p>

<p>
  <b>Status:</b>
  <%= if @article.isdisplayed then 'Currently Displayed' else 'Not Currently Displayed' end %>
</p>


<%= link_to 'Comments', article_comments_path(@article) %> |

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/articles/straightfromfaith.html.erb
<h1>Straight From Faithk</h1>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Author</th>
    
    <th></th>
  </tr>

<% @articles_SFF.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.user %></td>
    <td><%= article.author %></td>
    <td><%= link_to 'Show', article %></td>
    
  </tr>
<% end %>
 
</table>

<br />

app/views/articles/thebrain.html.erb
<h1>The Brain</h1>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Author</th>
    <th>Category</th>
    <th></th>
  </tr>

<% @articles_SFF.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.user %></td>
    <td><%= article.author %></td>
    <td><%= article.category.name %></td>
    <td><%= link_to 'Read Article', article %></td>

  </tr>
<% end %>
  <tr>
    <td colspan="10"> &nbsp;</td>
    <td colspan="10"> &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
  </tr>
 <tr>
    <th>Title</th>
    <th>User</th>
    <th>Author</th>
    <th>Category</th>
    <th></th>
  </tr>
  

<% @articles_FTD.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.user %></td>
    <td><%= article.author %></td>
    <td><%= article.category.name %></td>
    <td><%= link_to 'Read Article', article %></td>
 </tr>
<% end %>
<tr>
    <td colspan="10"> &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
    <td colspan="10"> &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
  </tr>
<tr>
    <th>Title</th>
    <th>User</th>
    <th>Author</th>
    <th>Category</th>
    <th></th>
  </tr>


<% @articles_TBN.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.user %></td>
    <td><%= article.author %></td>
    <td><%= article.category.name %></td>
    <td><%= link_to 'Read Article', article %></td>
  </tr>
<% end %>




<tr>
    <td colspan="10"> &nbsp;</td>
    <td colspan="10"> &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
    <td colspan="10">  &nbsp;</td>
   <td colspan="10">  &nbsp;</td>
  </tr>
<tr>
    <th>Title</th>
    <th>User</th>
    <th>Author</th>
    <th>Category</th>
    <th></th>
  </tr>

<% @articles_P.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.user %></td>
    <td><%= article.author %></td>
    <td><%= article.category.name %></td>
    <td><%= link_to 'Read Article', article %></td>
  </tr>
<% end %>




</table>

<br />

app/views/articles/thetalentbanknetwork.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Author</th>
    <th></th>
  </tr>

<% @articles_TBN.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.user %></td>
    <td><%= article.author %></td>
    <td><%= link_to 'Show', article %></td>
  </tr>
<% end %>
</table>

<br />