config/routes.rb
Brainreserve::Application.routes.draw do

  

  
  resources :invitations

  resources :articles do
      resources :comments
  end

  match '/comments/approve/:id' => 'comments#approve'
  match '/articles/toggledisplay/:id' => 'articles#toggledisplay'
  match '/thebrain' => 'articles#thebrain'
  match '/thebrain/straightfromfaith' => 'articles#straightfromfaith'
  match '/thebrain/fromthetrenddesk' => 'articles#fromthetrenddesk'
  match '/thebrain/predictions' => 'articles#predictions'
  match '/thebrain/thetalentnetwork' => 'articles#talentnetwork'
  
  
  resources :predictions
  resources :articles
  resources :comments

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  # GET /invitations
  # GET /invitations.xml
  def index
    @invitations = Invitation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @invitations }
    end
  end

  # GET /invitations/1
  # GET /invitations/1.xml
  def show
    @invitation = Invitation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @invitation }
    end
  end

  # GET /invitations/new
  # GET /invitations/new.xml
  def new
    @invitation = Invitation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @invitation }
    end
  end

  # GET /invitations/1/edit
  def edit
    @invitation = Invitation.find(params[:id])
  end

  # POST /invitations
  # POST /invitations.xml
  def create
    @invitation = Invitation.new(params[:invitation])

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to(@invitation, :notice => 'Invitation was successfully created.') }
        format.xml  { render :xml => @invitation, :status => :created, :location => @invitation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @invitation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /invitations/1
  # PUT /invitations/1.xml
  def update
    @invitation = Invitation.find(params[:id])

    respond_to do |format|
      if @invitation.update_attributes(params[:invitation])
        format.html { redirect_to(@invitation, :notice => 'Invitation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @invitation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.xml
  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy

    respond_to do |format|
      format.html { redirect_to(invitations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipient_email %><br />
    <%= f.text_field :recipient_email %>
  </div>
  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :sent_at %><br />
    <%= f.datetime_select :sent_at %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing invitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<h1>Listing invitations</h1>

<table>
  <tr>
    <th>Recipient email</th>
    <th>Token</th>
    <th>Sent at</th>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invitations.each do |invitation| %>
  <tr>
    <td><%= invitation.recipient_email %></td>
    <td><%= invitation.token %></td>
    <td><%= invitation.sent_at %></td>
    <td><%= invitation.message %></td>
    <td><%= link_to 'Show', invitation %></td>
    <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
    <td><%= link_to 'Destroy', invitation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Recipient email:</b>
  <%= @invitation.recipient_email %>
</p>

<p>
  <b>Token:</b>
  <%= @invitation.token %>
</p>

<p>
  <b>Sent at:</b>
  <%= @invitation.sent_at %>
</p>

<p>
  <b>Message:</b>
  <%= @invitation.message %>
</p>


<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>